schemaVersion: 2.1.0
metadata:
  name: ansible-demo
components:
  - name: tooling-container
    container:
      image: quay.io/ansible/creator-ee:latest
      volumeMounts:
        - name: venv
          path: /home/user/.venv
      memoryLimit: 2G
      mountSources: true
  - name: venv
    volume:
      size: 1G
