schemaVersion: 2.2.0
metadata:
  name: ansible-demo
components:
  - name: tooling-container
    container:
      image: quay.io/ansible/creator-ee:latest
      volumeMounts:
        - name: venv
          path: /home/user/.venv
      mountSources: true
  - name: venv
    volume:
      size: 1G          
      memoryRequest: 252M
      memoryLimit: 1Gi
      cpuRequest: 250m
      cpuLimit: 500m
      args: ['tail', '-f', '/dev/null']
